# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f66be8fb2bf965c031134c91f75dc40c46cf6014e96c6d617eb9c3ecec9d1b9ad39a9e1d5f16d54d835713899d9ab34325a1a29d3bdd9be1e59d410ce0f2af2

test:
  secret_key_base: 83ebff063d30b438da718637a7acb95b3dbf9b5646971ccb3c3471a6b19095b3a5b3825f47ffa26352962b44cbd1676ac4952d9890c1f38c534101e4d2849fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
